version: '3'
services:
  redis:
    image: redislabs/redisearch
    # volumes:
    #   - /externaldrive/postgres-data:/var/lib/postgresql/data
    restart: always
    # environment:
    #   POSTGRES_DB: ai_coe
    #   POSTGRES_USER: ai_coe_user
    #   POSTGRES_PASSWORD: immigrant_song123
    ports:
      - 6379:6379

networks:
  default:
    external:
      name: dev_network
