version: '3'
services:
  metabase:
    image: metabase/metabase
    # volumes:
    #   - /externaldrive/postgres-data:/var/lib/postgresql/data
    restart: always
    # environment:
    #   POSTGRES_DB: ai_coe
    #   POSTGRES_USER: ai_coe_user
    #   POSTGRES_PASSWORD: immigrant_song123
    ports:
      - 3000:3000

networks:
  default:
    external:
      name: dev_network
