EVENT_BROKER_TYPE = "REDIS"
EVENT_BROKER_URL = "redis://@localhost:6379/0" # "redis://[[username]:[password]]@localhost:6379/0"
# EVENT_BROKER_TOPIC = "CACHE-MERE"
EVENT_RECEIVER_URL = "http://localhost:5000/v1/event/receive"

EVENT_STREAM_NAME = "CACHE-MERE"
EVENT_CONSUMER_GROUP = "CACHE-MERE-CONSUMER-G"
EVENT_CONSUMER = "CACHE-MERE-CONSUMER"